package com.grizzly.core.lexer;

import java.util.Objects;

/**
 * Represents a single token in the Python template.
 * Using Java Record (JDK 16+) for immutability and conciseness.
 *
 * @param type   Token type (e.g., IDENTIFIER, NUMBER)
 * @param value  Token value for literals (e.g., "42" for NUMBER); null for operators
 * @param line   Line number (1-based)
 * @param column Column number (1-based)
 */
public record Token(TokenType type, String value, int line, int column) {
    
    /**
     * Compact constructor with validation
     */
    public Token {
        Objects.requireNonNull(type, "type cannot be null");
    }
    
    /**
     * Convenience constructor for tokens without values
     */
    public Token(TokenType type, int line, int column) {
        this(type, null, line, column);
    }
    
    /**
     * Custom toString for better debugging
     */
    @Override
    public String toString() {
        if (value != null) {
            return String.format("%s(%s) at %d:%d", type, value, line, column);
        }
        return String.format("%s at %d:%d", type, line, column);
    }
    
    // equals() and hashCode() are automatically generated by record!
}
